In [15]:
x = 'elQRGhkfFJC'

a = []
for i in x:
    a.append(i)
y = int(input())
a.remove(a[y])
sum1 = 0
for i in a:
    sum1 = sum1 + ord(i)
sum1

3


885

In [18]:
x = int(input())
sum1 = 0
for i in range(1,(x+1)):
    sum1 = sum1 + i
sum1

5


15

In [25]:
x = int(input())
y = int(input())

a = []
b = []
for i in range(0,x):
    t = int(input())
    a.append(t)
for j in range(0,y):
    ts = int(input())
    b.append(ts)
    
print(a)
print(b)

3
2
1
2
3
2
3
[0, 1, 2]
[0, 1]


In [41]:
x = 'Pp'

a = []
for i in x:
    a.append(i)
for i in a:
    if a.isupper() or a.islower()

['P', 'p']

In [ ]:
a = []
for i in range(0,8):
    a.append(i)


for i in a:
    c = 0
    for j in range(1,i):
        if i%j == 0:
            c += 1
    if c == 1:
            a.append(i)
a

In [67]:
x = 'ezfoedCywA'
x = x.lower()
a = []
b = []
for i in x:
    a.append(i)
for i in a:
    if i in 'aeiou':
        b.append(i)
len(b)

4

In [71]:
r = int(input())

a = []
b = []
for i in range(1,(r+1)):
    x = int(input())
    for j in range(1,(x+1)):
        t = int(input())
        a.append(t)
a

2
3
1
2
3
1
2


[1, 2, 3, 2]

In [85]:
X1 = 8
X2 = 1
X3 = 4
G = 6.673*(10**-11)
f = (G*X1*X2)/(X3**2)
print(int(f*(10**12)))

33


In [68]:
from itertools import permutations
X = 'xy'
p = permutations(X)
print(len(set([''.join(i) for i in list(p)])))

2


In [60]:
t = 'xiYOyljxPa'

a = []
for i in t:
    a.append(i)
y = a[::2]
sum1 = 0

for i in y:
    sum1 = sum1 + ord(i)
sum1

516

In [3]:
String = 'RzZyfQuUIpj'
String = String[0:1].upper() + String[1:len(String)-1] + String[len(String)-1:len(String)].upper()
a = []

for i in String:
    a.append(i)
sum1 = 0

for i in a:
    sum1 = sum1 + ord(i)
sum1

1059

In [ ]:
# Difference between array and list
# 1) long data for array
# 2) shape same for array
# 3) library import for array
# 4) arithmetic operation faster in array

In [23]:
city = ['Mumbai', 'Pune', 'Nagpur']

city

['Mumbai', 'Pune', 'Nagpur']

In [24]:
city.remove('Pune')

In [25]:
del city[0]
city

['Nagpur']

remove
del
pop
clear
del list_name

In [26]:
d1 = { 'A': 'Alpha', 'B': 'Bravo','C':'Charlie'}
d1

{'A': 'Alpha', 'B': 'Bravo', 'C': 'Charlie'}

In [27]:
l1 = []
for i in d1:
    l1.append(i)
    l1.append(d1[i])
l1

['A', 'Alpha', 'B', 'Bravo', 'C', 'Charlie']

In [28]:
# Ways to make use of a library
import math
math.sqrt(100)

10.0

In [29]:
import math as m
m.sqrt(100)

10.0

In [30]:
from math import sqrt
sqrt(100)

10.0

In [31]:
# m.exp (shift tab to read)

# numpy - numerical python

In [32]:
import numpy as np

In [33]:
l1 = [1,2,3,4]
l2 = [10,20,30,40]

In [34]:
l1

[1, 2, 3, 4]

In [35]:
l2

[10, 20, 30, 40]

In [36]:
l1 + l2

[1, 2, 3, 4, 10, 20, 30, 40]

In [37]:
arr1 = np.array(l1)
arr1

array([1, 2, 3, 4])

In [38]:
arr2 = np.array([10,20,30,40])   # 1 square brakcet means 1 D and 2 square means 2 D
arr2

array([10, 20, 30, 40])

In [39]:
print(arr2)

[10 20 30 40]


In [40]:
type(arr1)

numpy.ndarray

In [41]:
arr1 + arr2

array([11, 22, 33, 44])

In [42]:
l = [l1,l2]
l

[[1, 2, 3, 4], [10, 20, 30, 40]]

In [43]:
a2d = np.array(l)
a2d

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [44]:
arr1.ndim   # n means dimensions of array

1

In [45]:
a2d.ndim

2

In [46]:
arr1.shape    # in 1 D it tells the number of elements and others it tells rows and columns

(4,)

In [47]:
a2d.shape    

(2, 4)

In [48]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]

x = [a,b,c]

y = np.array(x)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
new_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(new_array)
print('')
print(new_array.ndim)
print('')
print(new_array.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

2

(3, 3)


In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [52]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [53]:
import numpy as np

x = np.arange(1,10).reshape(3,3)
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
# 2x4 even number
np.arange(2,18,2).reshape(2,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [58]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [60]:
np.zeros([2,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [61]:
np.zeros(8,dtype = int).reshape(2,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [62]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [63]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [64]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
np.eye(5)    # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [67]:
np.random.randint(1,101,size=5)    # method 1

array([71, 89, 89, 13, 59])

In [38]:
np.random.seed(0)
np.random.randint(1,101,9).reshape(3,3)

array([[45, 48, 65],
       [68, 68, 10],
       [84, 22, 37]])

In [68]:
from numpy.random import randint   # method 2

In [69]:
randint(1,51,5)

array([ 2, 39, 40, 24, 47])

# concept of seed

In [70]:
np.random.seed(0)     # control environment
np.random.randint(1,101,10)   # sequence should also be same

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [71]:
from numpy.random import randint,seed   # getting randint and seed at the same time from random

# selecting entries in array

In [72]:
np.random.seed(0)     
a = np.random.randint(1,101,10) 
a

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [73]:
np.random.seed(0)

b = np.random.randint(1,101,10)
b

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [74]:
a[1::3]

array([48, 68, 22])

In [75]:
a[0]

45

In [76]:
a[::-1]

array([88, 37, 22, 84, 10, 68, 68, 65, 48, 45])

In [77]:
a[::-2]

array([88, 22, 10, 68, 48])

In [78]:
len(a)

10

In [19]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
a[:,2]

array([ 3,  8, 13, 18, 23])

In [80]:
x = a[:,4]

In [81]:
b = np.arange(26,51).reshape(5,5)
b

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [83]:
y = b[:,4]

In [84]:
z = x+y
z

array([35, 45, 55, 65, 75])

In [97]:
a[-1]

array([21, 22, 23, 24, 25])

In [99]:
a[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [100]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [101]:
# a[start: stop+1:step]
a[1:4:2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [102]:
a[:3:2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [103]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# a[ROW,COLUMN]

In [104]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
a[0,0]

1

In [106]:
a[-1,-1]

25

In [107]:
a[2,3]

14

In [113]:
a[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [114]:
a[1:4:2,1:4]

array([[ 7,  8,  9],
       [17, 18, 19]])

# create a 10x10 array and select the following
1. select last 5 rows
2. select last 5 columns
3. reverse columns and select alternate

In [118]:
b = np.arange(1,101).reshape(10,10)
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [119]:
b[5:]

array([[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [121]:
b[:,5:]

array([[  6,   7,   8,   9,  10],
       [ 16,  17,  18,  19,  20],
       [ 26,  27,  28,  29,  30],
       [ 36,  37,  38,  39,  40],
       [ 46,  47,  48,  49,  50],
       [ 56,  57,  58,  59,  60],
       [ 66,  67,  68,  69,  70],
       [ 76,  77,  78,  79,  80],
       [ 86,  87,  88,  89,  90],
       [ 96,  97,  98,  99, 100]])

In [127]:
b[:,::-2]

array([[ 10,   8,   6,   4,   2],
       [ 20,  18,  16,  14,  12],
       [ 30,  28,  26,  24,  22],
       [ 40,  38,  36,  34,  32],
       [ 50,  48,  46,  44,  42],
       [ 60,  58,  56,  54,  52],
       [ 70,  68,  66,  64,  62],
       [ 80,  78,  76,  74,  72],
       [ 90,  88,  86,  84,  82],
       [100,  98,  96,  94,  92]])

In [128]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [133]:
b[4:7:2,2::2]

array([[43, 45, 47, 49],
       [63, 65, 67, 69]])

# fancy indexing

In [134]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [135]:
b[[1,2,1,5]]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [136]:
b[:,[5,5,3,1]]

array([[ 6,  6,  4,  2],
       [16, 16, 14, 12],
       [26, 26, 24, 22],
       [36, 36, 34, 32],
       [46, 46, 44, 42],
       [56, 56, 54, 52],
       [66, 66, 64, 62],
       [76, 76, 74, 72],
       [86, 86, 84, 82],
       [96, 96, 94, 92]])

In [137]:
b[[1,2,3],[1,2,3]]    # intersecting of rows and columns

array([12, 23, 34])

## Arithmetic operationon array

In [138]:
a = np.array([10,20,30,40])

In [139]:
a + 10

array([20, 30, 40, 50])

In [140]:
a*2

array([20, 40, 60, 80])

In [141]:
1/a

array([0.1       , 0.05      , 0.03333333, 0.025     ])

In [142]:
a**2

array([ 100,  400,  900, 1600], dtype=int32)

In [145]:
b = np.array([1,2,3,4])

In [143]:
a

array([10, 20, 30, 40])

In [146]:
b

array([1, 2, 3, 4])

In [147]:
a + b

array([11, 22, 33, 44])

In [148]:
a - b

array([ 9, 18, 27, 36])

In [149]:
a*b

array([ 10,  40,  90, 160])

In [150]:
a/b

array([10., 10., 10., 10.])

In [151]:
a

array([10, 20, 30, 40])

In [152]:
b

array([1, 2, 3, 4])

## Relational operators

In [153]:
a

array([10, 20, 30, 40])

In [154]:
a < 25

array([ True,  True, False, False])

In [155]:
marks = np.random.randint(1,101,10)
marks

array([71, 89, 89, 13, 59, 66, 40, 88, 47, 89])

In [156]:
marks < 40

array([False, False, False,  True, False, False, False, False, False,
       False])

In [157]:
marks[marks<40]

array([13])

In [158]:
marks > 40

array([ True,  True,  True, False,  True,  True, False,  True,  True,
        True])

In [159]:
marks < 80

array([ True, False, False,  True,  True,  True,  True, False,  True,
       False])

In [160]:
(marks > 40) & (marks < 80)

array([ True, False, False, False,  True,  True, False, False,  True,
       False])

In [161]:
marks[(marks > 40) & (marks < 80)]

array([71, 59, 66, 47])

# functions in numpy

In [163]:
a = np.array([1,2,3])
b = np.arange(1,10).reshape(3,3)

In [164]:
a

array([1, 2, 3])

In [165]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [167]:
np.exp(b)    # e to the power

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [168]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [169]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [170]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [171]:
np.mean(a)

2.0

In [172]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
np.mean(b)

5.0

In [174]:
np.mean(b,axis=0)    # axis zero is for columns

array([4., 5., 6.])

In [175]:
np.mean(b,axis=1)     # axis one is for rows

array([2., 5., 8.])

In [176]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [178]:
np.sum(b)

45

In [179]:
np.sum(b,axis=0)

array([12, 15, 18])

In [180]:
np.sum(b,axis=1)

array([ 6, 15, 24])

# concept of 3D 

In [43]:
a3d = np.arange(1,13).reshape(2,2,3)
a3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
x = np.arange(1,13).reshape(2,2,3)
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
a5 = np.arange(1,13).reshape(2,3,2)
a5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [182]:
a3d.ndim

3

# concept of concatenation

In [37]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

In [184]:
a

array([1, 2, 3, 4])

In [185]:
b

array([10, 20, 30, 40])

In [42]:
np.concatenate([a,b])

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [188]:
a1 = np.arange(1,7).reshape(2,3)
b1 = a1 + 10
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [189]:
b1

array([[11, 12, 13],
       [14, 15, 16]])

In [190]:
np.concatenate([a1,b1])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [191]:
np.concatenate([a1,b1], axis = 0)    # axis zero is the default value. even if we dont give it will take zero

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [192]:
np.concatenate([a1,b1], axis = 1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [193]:
np.concatenate([a,b], axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

# Stacking

In [44]:
a

array([1, 2, 3, 4])

In [45]:
b

array([10, 20, 30, 40])

In [197]:
np.hstack([a,b])     # h means horizontal

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [198]:
np.vstack([a,b])     # v means vertical

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [200]:
np.column_stack([a,b])

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

In [201]:
np.dstack([a,b])    # 3 D matrix

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30],
        [ 4, 40]]])

# Transpose

In [202]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [203]:
a1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
n1 = int(input())
n2 = int(input())

a = []

for j in range(n1,(n2+1)):
    x = j%10
    y = j//10
    if x != y:
        a.append(j)
len(a)

11
15


4

# Splitting

In [205]:
a2 = np.arange(1,9).reshape(2,4)
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [206]:
np.hsplit(a2,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [207]:
np.hsplit(a2,2)[0]

array([[1, 2],
       [5, 6]])

In [208]:
np.hsplit(a2,2)[1]

array([[3, 4],
       [7, 8]])

In [209]:
np.vsplit(a2,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [210]:
np.vsplit(a2,2)[0]

array([[1, 2, 3, 4]])

In [211]:
np.vsplit(a2,2)[1]

array([[5, 6, 7, 8]])

# loops in numpy

In [212]:
a

array([1, 2, 3, 4])

In [214]:
for i in a:
    print("value is",i)

value is 1
value is 2
value is 3
value is 4


In [215]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [216]:
for i in a1:
    print("value is",i)

value is [1 2 3]
value is [4 5 6]


In [217]:
for i in a1:
    for j in i:
        print(j)

1
2
3
4
5
6
