In [1]:
import numpy as np

In [2]:
num_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

x = np.ndarray.flatten(num_array)

a = []
for i in x:
    if i%2 == 0 and i!=2:
        a.append(i)
a

[4, 6, 8, 10]

In [154]:
# np.where(condition,true,false)
a = np.array([1,2,3,4])
b = np.array([100,200,300,400])
c1 = np.array([True,True,False,False])
np.where(c1,b,a)

array([100, 200,   3,   4])

In [155]:
# create a data of 10 students 1-100 seed 10
# replace data of failed students by 40. fail<40

In [156]:
np.random.seed(10)     
y = np.random.randint(1,101,10)
print(y)
np.where(y<40,40,y)

[10 16 65 29 90 94 30  9 74  1]


array([40, 40, 65, 40, 90, 94, 40, 40, 74, 40])

In [157]:
# to know the index position
np.where(y<40)


(array([0, 1, 3, 6, 7, 9], dtype=int64),)

# PANDAS

In [158]:
import pandas as pd

In [159]:
from pandas import Series

In [160]:
ser1 = Series([10,20,30,40])

In [161]:
ser1

0    10
1    20
2    30
3    40
dtype: int64

In [162]:
list('ABCDE')

['A', 'B', 'C', 'D', 'E']

In [20]:
lst = [11,12,13,14,15]

a = []
b = []

for i in lst:
    a.append(str(i))

for i in range(1,2):
    for j in a:
        y = list(j)
        b.append(y)


In [163]:
ser1 = Series([10,20,30,40,50], index = list('ABCDE'))
ser1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [164]:
ser1.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [165]:
ser1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [166]:
ser2 = Series({'BOM':'Mumbai','DEL':'Delhi','MAA':'Chennai'})
ser2

BOM     Mumbai
DEL      Delhi
MAA    Chennai
dtype: object

In [167]:
ser3 = Series(np.random.randint(1,101,10))
ser3

0    41
1    37
2    17
3    12
4    55
5    89
6    63
7    34
8    73
9    79
dtype: int32

# Selection of entries in a series

In [168]:
ser1

A    10
B    20
C    30
D    40
E    50
dtype: int64

# Grab by Index

In [169]:
ser1[0]

10

In [170]:
ser1[-1]

50

# Grab by Label

In [171]:
ser1['A']

10

In [172]:
ser1['E']

50

# Grab by Multiple Label

In [173]:
ser1[['A','E']]

A    10
E    50
dtype: int64

# Grab by range of Default Index

In [174]:
ser1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [175]:
ser1[:3]

A    10
B    20
C    30
dtype: int64

# Grab by Logic

In [176]:
ser1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [177]:
ser1 < 40    # it will give boolean

A     True
B     True
C     True
D    False
E    False
dtype: bool

In [178]:
ser1[(ser1<45) & (ser1>25)]

C    30
D    40
dtype: int64

In [179]:
ser1[ser1<40]   # it will give the values

A    10
B    20
C    30
dtype: int64

In [180]:
# Create two Series

In [181]:
np.random.seed(1)    
s1 = Series(np.random.randint(1,101,10), index = list('ABCDEFGHIJ'))
s2 = Series(np.random.randint(1,101,10), index = list('ABCDEFGHIJ'))
print(s1)
print(s2)
y = Series(np.where(s1 <40, s2, s1), s1.index)
print(y)

A    38
B    13
C    73
D    10
E    76
F     6
G    80
H    65
I    17
J     2
dtype: int32
A    77
B    72
C     7
D    26
E    51
F    21
G    19
H    85
I    12
J    29
dtype: int32
A    77
B    72
C    73
D    26
E    76
F    21
G    80
H    65
I    12
J    29
dtype: int32


# DataFrame

In [13]:
from pandas import DataFrame
import numpy as np

In [183]:
df1 = DataFrame(np.arange(1,26).reshape(5,5),index=list('ABCDE'),columns = list('XYZTU'))
df1

X   Y   Z   T   U
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20
E  21  22  23  24  25

In [184]:
print(df1)

    X   Y   Z   T   U
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20
E  21  22  23  24  25


In [185]:
df1 = DataFrame(np.arange(1,26).reshape(5,5),
               index=list('ABCDE'))
df1

0   1   2   3   4
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20
E  21  22  23  24  25

In [186]:
df1 = DataFrame(np.arange(1,26).reshape(5,5),
               index=list('ABCDE'),
               columns=['Col1','Col2','Col3','Col4','Col5'])
df1

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5
B     6     7     8     9    10
C    11    12    13    14    15
D    16    17    18    19    20
E    21    22    23    24    25

In [187]:
df1.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [188]:
df1.columns

Index(['Col1', 'Col2', 'Col3', 'Col4', 'Col5'], dtype='object')

In [189]:
df1.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [190]:
df2 = DataFrame([['Aniruddha','Kalbande',50,'Male'],
                ['Deepraj','Rathi',25,'Male'],
                ['Shreya','Iyer',20,'Female']],
                index=[100,101,102],
               columns=['FN','LN','age','Gender'])
df2

FN        LN  age  Gender
100  Aniruddha  Kalbande   50    Male
101    Deepraj     Rathi   25    Male
102     Shreya      Iyer   20  Female

In [191]:
df3 = DataFrame({'FirstName':['Aniket','Rahul','Kirti'],
                              'LastName':['Sharma','Joshi','Verma'],
                              'Age':[10,20,30],
                              'Salary': np.random.randint(10000,1000000,3)},index=[1,2,3])
df3

FirstName LastName  Age  Salary
1    Aniket   Sharma   10  198317
2     Rahul    Joshi   20  256322
3     Kirti    Verma   30  627028

# Selection techniques in DataFrame

# Grab by Column Name

In [192]:
df1['Col1']

A     1
B     6
C    11
D    16
E    21
Name: Col1, dtype: int32

In [193]:
df1['Col5']

A     5
B    10
C    15
D    20
E    25
Name: Col5, dtype: int32

# Grab by Multiple column

In [194]:
df1[['Col1','Col3']]

Col1  Col3
A     1     3
B     6     8
C    11    13
D    16    18
E    21    23

In [195]:
df1[['Col1']]

Col1
A     1
B     6
C    11
D    16
E    21

# Grab by range index

In [196]:
df1[1:3]

Col1  Col2  Col3  Col4  Col5
B     6     7     8     9    10
C    11    12    13    14    15

In [197]:
df1[:3]

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5
B     6     7     8     9    10
C    11    12    13    14    15

In [198]:
df1

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5
B     6     7     8     9    10
C    11    12    13    14    15
D    16    17    18    19    20
E    21    22    23    24    25

In [199]:
df1['Col1']<15

A     True
B     True
C     True
D    False
E    False
Name: Col1, dtype: bool

In [200]:
df1[df1['Col1']<15]

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5
B     6     7     8     9    10
C    11    12    13    14    15

In [201]:
df2

FN        LN  age  Gender
100  Aniruddha  Kalbande   50    Male
101    Deepraj     Rathi   25    Male
102     Shreya      Iyer   20  Female

In [202]:
df2['Gender'] == 'Female'

100    False
101    False
102     True
Name: Gender, dtype: bool

In [203]:
df2[df2['Gender']=='Female']

FN    LN  age  Gender
102  Shreya  Iyer   20  Female

In [204]:
df2[df2['Gender']=='Female']['LN']

102    Iyer
Name: LN, dtype: object

In [205]:
df2[(df2['age'] >30) & (df2['Gender']=='Male')]

FN        LN  age Gender
100  Aniruddha  Kalbande   50   Male

In [206]:
#step_1- df2['Gender'] == 'Male'
#step_2- df2['Age'] > 30
#step_3- (df2['Gender'] == 'Male') & (df2['Age'] > 30)
#step_4- df2[(df2['Gender'] == 'Male') & (df2['Age'] > 30)]

In [207]:
np.random.seed(0)
df4 = DataFrame({'Company_Name':['Facebook','Google','Microsoft','Yahoo','Instagram'],
                              'Ticker':['FB','GL','MI','YH','IG'],
                              'Price': np.random.randint(500,5000,5)},index=[1,2,3,4,5])
df4

Company_Name Ticker  Price
1     Facebook     FB   3232
2       Google     GL   3107
3    Microsoft     MI   2153
4        Yahoo     YH   3764
5    Instagram     IG   1533

In [208]:
df4['Price_GST']= df4['Price']*1.18
df4

Company_Name Ticker  Price  Price_GST
1     Facebook     FB   3232    3813.76
2       Google     GL   3107    3666.26
3    Microsoft     MI   2153    2540.54
4        Yahoo     YH   3764    4441.52
5    Instagram     IG   1533    1808.94

In [209]:
df4['Country'] = ['India','USA','USA','India','India']
df4

Company_Name Ticker  Price  Price_GST Country
1     Facebook     FB   3232    3813.76   India
2       Google     GL   3107    3666.26     USA
3    Microsoft     MI   2153    2540.54     USA
4        Yahoo     YH   3764    4441.52   India
5    Instagram     IG   1533    1808.94   India

In [210]:
# select india and price_gst greater than 3k
df4[(df4['Country'] == 'India')  & (df4['Price_GST'] > 3000)]

Company_Name Ticker  Price  Price_GST Country
1     Facebook     FB   3232    3813.76   India
4        Yahoo     YH   3764    4441.52   India

In [211]:
# select price between 2k and 4k
df4[(df4['Price_GST'] >2000) & (df4['Price_GST'] <4000)]

Company_Name Ticker  Price  Price_GST Country
1     Facebook     FB   3232    3813.76   India
2       Google     GL   3107    3666.26     USA
3    Microsoft     MI   2153    2540.54     USA

In [212]:
# fetch only ticker of country USA and price less than 3k
df4[(df4['Price_GST'] <3000) & (df4['Country'] == 'USA')]['Ticker']

3    MI
Name: Ticker, dtype: object

In [213]:
df4[(df4['Price_GST'] <3000) & (df4['Country'] == 'USA')][['Ticker','Country']]

Ticker Country
3     MI     USA

# selection of entries using loc and iloc

# iloc

In [214]:
df1

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5
B     6     7     8     9    10
C    11    12    13    14    15
D    16    17    18    19    20
E    21    22    23    24    25

In [215]:
df1.iloc[0]

Col1    1
Col2    2
Col3    3
Col4    4
Col5    5
Name: A, dtype: int32

In [216]:
df1.iloc[[0]]

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5

In [217]:
df1.iloc[-1]

Col1    21
Col2    22
Col3    23
Col4    24
Col5    25
Name: E, dtype: int32

In [218]:
df1.iloc[:3]

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5
B     6     7     8     9    10
C    11    12    13    14    15

In [219]:
df1.iloc[-3:]

Col1  Col2  Col3  Col4  Col5
C    11    12    13    14    15
D    16    17    18    19    20
E    21    22    23    24    25

In [220]:
df1.iloc[0,0]

1

In [221]:
df1.iloc[-1,-1]

25

In [222]:
df1.iloc[:,1]

A     2
B     7
C    12
D    17
E    22
Name: Col2, dtype: int32

In [223]:
df1.iloc[:,1:4]

Col2  Col3  Col4
A     2     3     4
B     7     8     9
C    12    13    14
D    17    18    19
E    22    23    24

In [224]:
df1.iloc[::2,-2:]

Col4  Col5
A     4     5
C    14    15
E    24    25

In [225]:
df1

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5
B     6     7     8     9    10
C    11    12    13    14    15
D    16    17    18    19    20
E    21    22    23    24    25

# loc

In [133]:
df1.loc['A']

Col1    1
Col2    2
Col3    3
Col4    4
Col5    5
Name: A, dtype: int32

In [134]:
df1.loc[['A']]

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5

In [135]:
df1.loc[['A','D','E']]

Col1  Col2  Col3  Col4  Col5
A     1     2     3     4     5
D    16    17    18    19    20
E    21    22    23    24    25

In [136]:
df1.loc['A','Col1']

1

In [137]:
df1.loc['E','Col5']

25

In [138]:
df1.loc[:,'Col1']

A     1
B     6
C    11
D    16
E    21
Name: Col1, dtype: int32

In [139]:
df1.loc[:,['Col1']]

Col1
A     1
B     6
C    11
D    16
E    21

In [140]:
df1.loc[:,['Col1','Col5']]

Col1  Col5
A     1     5
B     6    10
C    11    15
D    16    20
E    21    25

In [141]:
df4

Company_Name Ticker  Price Country  Price_GST
1     Facebook     FB   3232   India    3813.76
2       Google     GL   3107     USA    3666.26
3    Microsoft     MI   2153     USA    2540.54
4        Yahoo     YH   3764   India    4441.52
5    Instagram     IG   1533   India    1808.94

In [151]:
df4.loc[:,['Company_Name','Ticker','Price','Price_GST']]

Company_Name Ticker  Price  Price_GST
1     Facebook     FB   3232    3813.76
2       Google     GL   3107    3666.26
3    Microsoft     MI   2153    2540.54
4        Yahoo     YH   3764    4441.52
5    Instagram     IG   1533    1808.94

In [160]:
df4.loc[:, df4.columns != 'Country']

Company_Name Ticker  Price  Price_GST
1     Facebook     FB   3232    3813.76
2       Google     GL   3107    3666.26
3    Microsoft     MI   2153    2540.54
4        Yahoo     YH   3764    4441.52
5    Instagram     IG   1533    1808.94

# Sorting

In [161]:
df3

FirstName LastName  Age  Salary
1    Aniket   Sharma   10  198317
2     Rahul    Joshi   20  256322
3     Kirti    Verma   30  627028

In [9]:
np.random.seed(0)
df6 = DataFrame({'Name':list('ABCDEFGHIJ'),
                'Marks 1': np.random.randint(1,101,10),
                'Marks 2': np.random.randint(1,101,10)})
df6.iloc[1:3,1] = 85
df6

Name  Marks 1  Marks 2
0    A       45       71
1    B       85       89
2    C       85       89
3    D       68       13
4    E       68       59
5    F       10       66
6    G       84       40
7    H       22       88
8    I       37       47
9    J       88       89

In [163]:
df6.sort_values(by='Marks 1')

Name  Marks 1  Marks 2
5    F       10       66
7    H       22       88
8    I       37       47
0    A       45       71
3    D       68       13
4    E       68       59
6    G       84       40
1    B       85       89
2    C       85       89
9    J       88       89

In [164]:
df6.sort_values(by='Marks 1',ascending=False)

Name  Marks 1  Marks 2
9    J       88       89
1    B       85       89
2    C       85       89
6    G       84       40
3    D       68       13
4    E       68       59
0    A       45       71
8    I       37       47
7    H       22       88
5    F       10       66

In [165]:
df6

Name  Marks 1  Marks 2
0    A       45       71
1    B       85       89
2    C       85       89
3    D       68       13
4    E       68       59
5    F       10       66
6    G       84       40
7    H       22       88
8    I       37       47
9    J       88       89

In [166]:
df6.sort_values(by='Marks 1',ascending = False, inplace=True)

In [167]:
df6

Name  Marks 1  Marks 2
9    J       88       89
1    B       85       89
2    C       85       89
6    G       84       40
3    D       68       13
4    E       68       59
0    A       45       71
8    I       37       47
7    H       22       88
5    F       10       66

In [168]:
df6.sort_index(inplace=True)

In [170]:
df6.sort_values(by=['Marks 1','Marks 2'])

Name  Marks 1  Marks 2
5    F       10       66
7    H       22       88
8    I       37       47
0    A       45       71
3    D       68       13
4    E       68       59
6    G       84       40
1    B       85       89
2    C       85       89
9    J       88       89

In [171]:
df6.sort_values(by=['Marks 1','Marks 2'], ascending = [False,True])

Name  Marks 1  Marks 2
9    J       88       89
1    B       85       89
2    C       85       89
6    G       84       40
3    D       68       13
4    E       68       59
0    A       45       71
8    I       37       47
7    H       22       88
5    F       10       66

# Ranks

In [172]:
df7 = DataFrame({'Marks': np.array([10,15,30,30,50])})
df7

Marks
0     10
1     15
2     30
3     30
4     50

# least value least Rank

In [174]:
df7['Rank Avg'] = df7['Marks'].rank()  # default ,method = average
df7

Marks  Rank Avg
0     10       1.0
1     15       2.0
2     30       3.5
3     30       3.5
4     50       5.0

In [175]:
df7['Rank Min'] = df7['Marks'].rank(method='min')
df7

Marks  Rank Avg  Rank Min
0     10       1.0       1.0
1     15       2.0       2.0
2     30       3.5       3.0
3     30       3.5       3.0
4     50       5.0       5.0

In [176]:
df7['Rank Max'] = df7['Marks'].rank(method='max')
df7

Marks  Rank Avg  Rank Min  Rank Max
0     10       1.0       1.0       1.0
1     15       2.0       2.0       2.0
2     30       3.5       3.0       4.0
3     30       3.5       3.0       4.0
4     50       5.0       5.0       5.0

In [177]:
df7['Rank Dense'] = df7['Marks'].rank(method='dense')
df7

Marks  Rank Avg  Rank Min  Rank Max  Rank Dense
0     10       1.0       1.0       1.0         1.0
1     15       2.0       2.0       2.0         2.0
2     30       3.5       3.0       4.0         3.0
3     30       3.5       3.0       4.0         3.0
4     50       5.0       5.0       5.0         4.0

In [178]:
df7['Rank First'] = df7['Marks'].rank(method='first')
df7

Marks  Rank Avg  Rank Min  Rank Max  Rank Dense  Rank First
0     10       1.0       1.0       1.0         1.0         1.0
1     15       2.0       2.0       2.0         2.0         2.0
2     30       3.5       3.0       4.0         3.0         3.0
3     30       3.5       3.0       4.0         3.0         4.0
4     50       5.0       5.0       5.0         4.0         5.0

In [179]:
df7['Rank Avg Reverse'] = df7['Marks'].rank(ascending= False)
df7

Marks  Rank Avg  Rank Min  Rank Max  Rank Dense  Rank First  \
0     10       1.0       1.0       1.0         1.0         1.0   
1     15       2.0       2.0       2.0         2.0         2.0   
2     30       3.5       3.0       4.0         3.0         3.0   
3     30       3.5       3.0       4.0         3.0         4.0   
4     50       5.0       5.0       5.0         4.0         5.0   

   Rank Avg Reverse  
0               5.0  
1               4.0  
2               2.5  
3               2.5  
4               1.0

In [180]:
df8 = DataFrame({'Name':['Aniruddha Kalbande','Raju Rastogi']})

In [181]:
df8['Name'].str.split()

0    [Aniruddha, Kalbande]
1          [Raju, Rastogi]
Name: Name, dtype: object

In [182]:
df8['Name'].str.split(expand=True)

0         1
0  Aniruddha  Kalbande
1       Raju   Rastogi

In [183]:
df8[['FN','LN']] = df8['Name'].str.split(expand=True)
df8

Name         FN        LN
0  Aniruddha Kalbande  Aniruddha  Kalbande
1        Raju Rastogi       Raju   Rastogi